// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calendar.proto

package schema

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Title                string               `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Descr                string               `protobuf:"bytes,4,opt,name=descr,proto3" json:"descr,omitempty"`
	UserID               int64                `protobuf:"varint,5,opt,name=userID,proto3" json:"userID,omitempty"`
	DurationStart        *duration.Duration   `protobuf:"bytes,6,opt,name=durationStart,proto3" json:"durationStart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Event) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Event) GetDescr() string {
	if m != nil {
		return m.Descr
	}
	return ""
}

func (m *Event) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Event) GetDurationStart() *duration.Duration {
	if m != nil {
		return m.DurationStart
	}
	return nil
}

// Create
type CreateRpcRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRpcRequest) Reset()         { *m = CreateRpcRequest{} }
func (m *CreateRpcRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRpcRequest) ProtoMessage()    {}
func (*CreateRpcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{1}
}

func (m *CreateRpcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRpcRequest.Unmarshal(m, b)
}
func (m *CreateRpcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRpcRequest.Marshal(b, m, deterministic)
}
func (m *CreateRpcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRpcRequest.Merge(m, src)
}
func (m *CreateRpcRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRpcRequest.Size(m)
}
func (m *CreateRpcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRpcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRpcRequest proto.InternalMessageInfo

func (m *CreateRpcRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type CreateRpcResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRpcResponse) Reset()         { *m = CreateRpcResponse{} }
func (m *CreateRpcResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRpcResponse) ProtoMessage()    {}
func (*CreateRpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{2}
}

func (m *CreateRpcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRpcResponse.Unmarshal(m, b)
}
func (m *CreateRpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRpcResponse.Marshal(b, m, deterministic)
}
func (m *CreateRpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRpcResponse.Merge(m, src)
}
func (m *CreateRpcResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRpcResponse.Size(m)
}
func (m *CreateRpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRpcResponse proto.InternalMessageInfo

func (m *CreateRpcResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Update
type UpdateRpcRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Event                *Event   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRpcRequest) Reset()         { *m = UpdateRpcRequest{} }
func (m *UpdateRpcRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRpcRequest) ProtoMessage()    {}
func (*UpdateRpcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{3}
}

func (m *UpdateRpcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRpcRequest.Unmarshal(m, b)
}
func (m *UpdateRpcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRpcRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRpcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRpcRequest.Merge(m, src)
}
func (m *UpdateRpcRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRpcRequest.Size(m)
}
func (m *UpdateRpcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRpcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRpcRequest proto.InternalMessageInfo

func (m *UpdateRpcRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRpcRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

// Delete
type DeleteRpcRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRpcRequest) Reset()         { *m = DeleteRpcRequest{} }
func (m *DeleteRpcRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRpcRequest) ProtoMessage()    {}
func (*DeleteRpcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{4}
}

func (m *DeleteRpcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRpcRequest.Unmarshal(m, b)
}
func (m *DeleteRpcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRpcRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRpcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRpcRequest.Merge(m, src)
}
func (m *DeleteRpcRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRpcRequest.Size(m)
}
func (m *DeleteRpcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRpcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRpcRequest proto.InternalMessageInfo

func (m *DeleteRpcRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// GetListByDate
type GetListByDateRpcRequest struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetListByDateRpcRequest) Reset()         { *m = GetListByDateRpcRequest{} }
func (m *GetListByDateRpcRequest) String() string { return proto.CompactTextString(m) }
func (*GetListByDateRpcRequest) ProtoMessage()    {}
func (*GetListByDateRpcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{5}
}

func (m *GetListByDateRpcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListByDateRpcRequest.Unmarshal(m, b)
}
func (m *GetListByDateRpcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListByDateRpcRequest.Marshal(b, m, deterministic)
}
func (m *GetListByDateRpcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListByDateRpcRequest.Merge(m, src)
}
func (m *GetListByDateRpcRequest) XXX_Size() int {
	return xxx_messageInfo_GetListByDateRpcRequest.Size(m)
}
func (m *GetListByDateRpcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListByDateRpcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListByDateRpcRequest proto.InternalMessageInfo

func (m *GetListByDateRpcRequest) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type GetListByDateRpcResponse struct {
	Event                []*Event `protobuf:"bytes,1,rep,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListByDateRpcResponse) Reset()         { *m = GetListByDateRpcResponse{} }
func (m *GetListByDateRpcResponse) String() string { return proto.CompactTextString(m) }
func (*GetListByDateRpcResponse) ProtoMessage()    {}
func (*GetListByDateRpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{6}
}

func (m *GetListByDateRpcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListByDateRpcResponse.Unmarshal(m, b)
}
func (m *GetListByDateRpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListByDateRpcResponse.Marshal(b, m, deterministic)
}
func (m *GetListByDateRpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListByDateRpcResponse.Merge(m, src)
}
func (m *GetListByDateRpcResponse) XXX_Size() int {
	return xxx_messageInfo_GetListByDateRpcResponse.Size(m)
}
func (m *GetListByDateRpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListByDateRpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListByDateRpcResponse proto.InternalMessageInfo

func (m *GetListByDateRpcResponse) GetEvent() []*Event {
	if m != nil {
		return m.Event
	}
	return nil
}

// GetListByWeek
type GetListByWeekRpcRequest struct {
	Start                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetListByWeekRpcRequest) Reset()         { *m = GetListByWeekRpcRequest{} }
func (m *GetListByWeekRpcRequest) String() string { return proto.CompactTextString(m) }
func (*GetListByWeekRpcRequest) ProtoMessage()    {}
func (*GetListByWeekRpcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{7}
}

func (m *GetListByWeekRpcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListByWeekRpcRequest.Unmarshal(m, b)
}
func (m *GetListByWeekRpcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListByWeekRpcRequest.Marshal(b, m, deterministic)
}
func (m *GetListByWeekRpcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListByWeekRpcRequest.Merge(m, src)
}
func (m *GetListByWeekRpcRequest) XXX_Size() int {
	return xxx_messageInfo_GetListByWeekRpcRequest.Size(m)
}
func (m *GetListByWeekRpcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListByWeekRpcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListByWeekRpcRequest proto.InternalMessageInfo

func (m *GetListByWeekRpcRequest) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

type GetListByWeekRpcResponse struct {
	Event                []*Event `protobuf:"bytes,1,rep,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListByWeekRpcResponse) Reset()         { *m = GetListByWeekRpcResponse{} }
func (m *GetListByWeekRpcResponse) String() string { return proto.CompactTextString(m) }
func (*GetListByWeekRpcResponse) ProtoMessage()    {}
func (*GetListByWeekRpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{8}
}

func (m *GetListByWeekRpcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListByWeekRpcResponse.Unmarshal(m, b)
}
func (m *GetListByWeekRpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListByWeekRpcResponse.Marshal(b, m, deterministic)
}
func (m *GetListByWeekRpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListByWeekRpcResponse.Merge(m, src)
}
func (m *GetListByWeekRpcResponse) XXX_Size() int {
	return xxx_messageInfo_GetListByWeekRpcResponse.Size(m)
}
func (m *GetListByWeekRpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListByWeekRpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListByWeekRpcResponse proto.InternalMessageInfo

func (m *GetListByWeekRpcResponse) GetEvent() []*Event {
	if m != nil {
		return m.Event
	}
	return nil
}

// GetListByMonth
type GetListByMonthRpcRequest struct {
	Start                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetListByMonthRpcRequest) Reset()         { *m = GetListByMonthRpcRequest{} }
func (m *GetListByMonthRpcRequest) String() string { return proto.CompactTextString(m) }
func (*GetListByMonthRpcRequest) ProtoMessage()    {}
func (*GetListByMonthRpcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{9}
}

func (m *GetListByMonthRpcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListByMonthRpcRequest.Unmarshal(m, b)
}
func (m *GetListByMonthRpcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListByMonthRpcRequest.Marshal(b, m, deterministic)
}
func (m *GetListByMonthRpcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListByMonthRpcRequest.Merge(m, src)
}
func (m *GetListByMonthRpcRequest) XXX_Size() int {
	return xxx_messageInfo_GetListByMonthRpcRequest.Size(m)
}
func (m *GetListByMonthRpcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListByMonthRpcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListByMonthRpcRequest proto.InternalMessageInfo

func (m *GetListByMonthRpcRequest) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

type GetListByMonthRpcResponse struct {
	Event                []*Event `protobuf:"bytes,1,rep,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListByMonthRpcResponse) Reset()         { *m = GetListByMonthRpcResponse{} }
func (m *GetListByMonthRpcResponse) String() string { return proto.CompactTextString(m) }
func (*GetListByMonthRpcResponse) ProtoMessage()    {}
func (*GetListByMonthRpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{10}
}

func (m *GetListByMonthRpcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListByMonthRpcResponse.Unmarshal(m, b)
}
func (m *GetListByMonthRpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListByMonthRpcResponse.Marshal(b, m, deterministic)
}
func (m *GetListByMonthRpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListByMonthRpcResponse.Merge(m, src)
}
func (m *GetListByMonthRpcResponse) XXX_Size() int {
	return xxx_messageInfo_GetListByMonthRpcResponse.Size(m)
}
func (m *GetListByMonthRpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListByMonthRpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListByMonthRpcResponse proto.InternalMessageInfo

func (m *GetListByMonthRpcResponse) GetEvent() []*Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*CreateRpcRequest)(nil), "CreateRpcRequest")
	proto.RegisterType((*CreateRpcResponse)(nil), "CreateRpcResponse")
	proto.RegisterType((*UpdateRpcRequest)(nil), "UpdateRpcRequest")
	proto.RegisterType((*DeleteRpcRequest)(nil), "DeleteRpcRequest")
	proto.RegisterType((*GetListByDateRpcRequest)(nil), "GetListByDateRpcRequest")
	proto.RegisterType((*GetListByDateRpcResponse)(nil), "GetListByDateRpcResponse")
	proto.RegisterType((*GetListByWeekRpcRequest)(nil), "GetListByWeekRpcRequest")
	proto.RegisterType((*GetListByWeekRpcResponse)(nil), "GetListByWeekRpcResponse")
	proto.RegisterType((*GetListByMonthRpcRequest)(nil), "GetListByMonthRpcRequest")
	proto.RegisterType((*GetListByMonthRpcResponse)(nil), "GetListByMonthRpcResponse")
}

func init() {
	proto.RegisterFile("calendar.proto", fileDescriptor_e3d25d49f056cdb2)
}

var fileDescriptor_e3d25d49f056cdb2 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x14, 0x8c, 0xe3, 0xda, 0x0a, 0xaf, 0x6a, 0x94, 0xac, 0x50, 0x71, 0x0c, 0x82, 0x68, 0xb9, 0xe4,
	0xb4, 0x2d, 0x41, 0x95, 0xe0, 0x04, 0x6a, 0x53, 0x50, 0x44, 0xb9, 0x18, 0x10, 0x12, 0x37, 0x37,
	0x7e, 0xb4, 0x16, 0x89, 0x6d, 0xbc, 0x2f, 0x48, 0xfd, 0x01, 0x7e, 0x98, 0x1f, 0x40, 0xde, 0xb5,
	0x8b, 0xbd, 0x6e, 0x9a, 0x48, 0x1c, 0xd7, 0x3b, 0x6f, 0x66, 0xf6, 0xcd, 0x18, 0xfa, 0x8b, 0x70,
	0x89, 0x49, 0x14, 0xe6, 0x22, 0xcb, 0x53, 0x4a, 0xfd, 0x67, 0x57, 0x69, 0x7a, 0xb5, 0xc4, 0x23,
	0x75, 0xba, 0x5c, 0x7f, 0x3f, 0xa2, 0x78, 0x85, 0x92, 0xc2, 0x55, 0x56, 0x02, 0x9e, 0x9a, 0x80,
	0x68, 0x9d, 0x87, 0x14, 0xa7, 0x49, 0x79, 0xff, 0xd8, 0xbc, 0xc7, 0x55, 0x46, 0x37, 0xfa, 0x92,
	0xff, 0xb1, 0xc0, 0x39, 0xff, 0x85, 0x09, 0xb1, 0x87, 0xe0, 0x50, 0x4c, 0x4b, 0xf4, 0xac, 0xb1,
	0x35, 0x79, 0x10, 0xe8, 0x03, 0x13, 0xb0, 0x17, 0x85, 0x84, 0x5e, 0x77, 0x6c, 0x4d, 0xf6, 0xa7,
	0xbe, 0xd0, 0x5c, 0xa2, 0xe2, 0x12, 0x9f, 0x2b, 0x33, 0x81, 0xc2, 0xb1, 0x13, 0xe8, 0x55, 0xf2,
	0x9e, 0xad, 0x66, 0x46, 0xad, 0x99, 0x59, 0x09, 0x08, 0x6e, 0xa1, 0x85, 0x78, 0x84, 0x72, 0x91,
	0x7b, 0x7b, 0x5a, 0x5c, 0x1d, 0xd8, 0x21, 0xb8, 0x6b, 0x89, 0xf9, 0x7c, 0xe6, 0x39, 0x63, 0x6b,
	0x62, 0x07, 0xe5, 0x89, 0xbd, 0x81, 0x83, 0x6a, 0xf2, 0x13, 0x85, 0x39, 0x79, 0xee, 0x36, 0xa5,
	0x26, 0x9e, 0x1f, 0xc3, 0xe0, 0x2c, 0xc7, 0x90, 0x30, 0xc8, 0x16, 0x01, 0xfe, 0x5c, 0xa3, 0x24,
	0xf6, 0x04, 0x1c, 0x2c, 0x16, 0xa1, 0xde, 0xbf, 0x3f, 0x75, 0x85, 0x5a, 0x4b, 0xa0, 0x3f, 0xf2,
	0xe7, 0x30, 0xac, 0x4d, 0xc8, 0x2c, 0x4d, 0x24, 0xb2, 0x3e, 0x74, 0xe3, 0x48, 0xe1, 0xed, 0xa0,
	0x1b, 0x47, 0xfc, 0x2d, 0x0c, 0xbe, 0x64, 0x51, 0x93, 0xd6, 0xc0, 0xfc, 0x93, 0xe9, 0xde, 0x25,
	0xc3, 0x61, 0x30, 0xc3, 0x25, 0xde, 0xc7, 0xc0, 0xe7, 0xf0, 0xe8, 0x3d, 0xd2, 0x45, 0x2c, 0xe9,
	0xf4, 0x66, 0xd6, 0x14, 0xab, 0xd2, 0xb2, 0x76, 0x4b, 0x8b, 0xbf, 0x02, 0xaf, 0x4d, 0x55, 0x3e,
	0xae, 0xb6, 0x0f, 0xbb, 0x6d, 0xf4, 0x43, 0xcd, 0xc4, 0x57, 0xc4, 0x1f, 0x35, 0x13, 0xc7, 0xe0,
	0x48, 0x95, 0xca, 0x76, 0x17, 0x1a, 0xd8, 0xb0, 0x71, 0x4b, 0xb6, 0x93, 0x8d, 0x8b, 0xda, 0xe4,
	0xc7, 0x34, 0xa1, 0xeb, 0xff, 0xf2, 0xf1, 0x1a, 0x46, 0x77, 0xb0, 0xed, 0x62, 0x64, 0xfa, 0xdb,
	0x86, 0xde, 0x59, 0xf9, 0xe3, 0xb2, 0x17, 0xe0, 0xea, 0xb2, 0xb0, 0xa1, 0x30, 0x7b, 0xe6, 0x33,
	0xd1, 0x2a, 0x12, 0xef, 0xb0, 0x13, 0x70, 0x75, 0x75, 0xd8, 0x50, 0x98, 0x1d, 0xf2, 0x0f, 0x5b,
	0xd6, 0xcf, 0x8b, 0x5f, 0x58, 0x8f, 0xe9, 0xbe, 0xb0, 0xa1, 0x30, 0x8b, 0x73, 0xcf, 0xd8, 0x3b,
	0x38, 0x68, 0xe4, 0xce, 0x3c, 0xb1, 0xa1, 0x52, 0xfe, 0x48, 0x6c, 0x6a, 0x88, 0xc1, 0x53, 0x04,
	0x57, 0xe7, 0x69, 0xb6, 0xa2, 0xce, 0x63, 0x44, 0xcc, 0x3b, 0x6c, 0x0e, 0xfd, 0xe6, 0xe2, 0x59,
	0x0d, 0x6e, 0xe4, 0xea, 0xfb, 0x62, 0x63, 0x48, 0xbc, 0x73, 0xda, 0xfb, 0xe6, 0xca, 0xc5, 0x35,
	0xae, 0xc2, 0x4b, 0x57, 0x3d, 0xfb, 0xe5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0x01, 0xcc,
	0x1b, 0x51, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalendarClient is the client API for Calendar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalendarClient interface {
	Create(ctx context.Context, in *CreateRpcRequest, opts ...grpc.CallOption) (*CreateRpcResponse, error)
	Update(ctx context.Context, in *UpdateRpcRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *DeleteRpcRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetListByDate(ctx context.Context, in *GetListByDateRpcRequest, opts ...grpc.CallOption) (*GetListByDateRpcResponse, error)
	GetListByWeek(ctx context.Context, in *GetListByWeekRpcRequest, opts ...grpc.CallOption) (*GetListByWeekRpcResponse, error)
	GetListByMonth(ctx context.Context, in *GetListByMonthRpcRequest, opts ...grpc.CallOption) (*GetListByMonthRpcResponse, error)
}

type calendarClient struct {
	cc grpc.ClientConnInterface
}

func NewCalendarClient(cc grpc.ClientConnInterface) CalendarClient {
	return &calendarClient{cc}
}

func (c *calendarClient) Create(ctx context.Context, in *CreateRpcRequest, opts ...grpc.CallOption) (*CreateRpcResponse, error) {
	out := new(CreateRpcResponse)
	err := c.cc.Invoke(ctx, "/Calendar/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) Update(ctx context.Context, in *UpdateRpcRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Calendar/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) Delete(ctx context.Context, in *DeleteRpcRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Calendar/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) GetListByDate(ctx context.Context, in *GetListByDateRpcRequest, opts ...grpc.CallOption) (*GetListByDateRpcResponse, error) {
	out := new(GetListByDateRpcResponse)
	err := c.cc.Invoke(ctx, "/Calendar/GetListByDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) GetListByWeek(ctx context.Context, in *GetListByWeekRpcRequest, opts ...grpc.CallOption) (*GetListByWeekRpcResponse, error) {
	out := new(GetListByWeekRpcResponse)
	err := c.cc.Invoke(ctx, "/Calendar/GetListByWeek", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) GetListByMonth(ctx context.Context, in *GetListByMonthRpcRequest, opts ...grpc.CallOption) (*GetListByMonthRpcResponse, error) {
	out := new(GetListByMonthRpcResponse)
	err := c.cc.Invoke(ctx, "/Calendar/GetListByMonth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarServer is the server API for Calendar service.
type CalendarServer interface {
	Create(context.Context, *CreateRpcRequest) (*CreateRpcResponse, error)
	Update(context.Context, *UpdateRpcRequest) (*empty.Empty, error)
	Delete(context.Context, *DeleteRpcRequest) (*empty.Empty, error)
	GetListByDate(context.Context, *GetListByDateRpcRequest) (*GetListByDateRpcResponse, error)
	GetListByWeek(context.Context, *GetListByWeekRpcRequest) (*GetListByWeekRpcResponse, error)
	GetListByMonth(context.Context, *GetListByMonthRpcRequest) (*GetListByMonthRpcResponse, error)
}

// UnimplementedCalendarServer can be embedded to have forward compatible implementations.
type UnimplementedCalendarServer struct {
}

func (*UnimplementedCalendarServer) Create(ctx context.Context, req *CreateRpcRequest) (*CreateRpcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedCalendarServer) Update(ctx context.Context, req *UpdateRpcRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedCalendarServer) Delete(ctx context.Context, req *DeleteRpcRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedCalendarServer) GetListByDate(ctx context.Context, req *GetListByDateRpcRequest) (*GetListByDateRpcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListByDate not implemented")
}
func (*UnimplementedCalendarServer) GetListByWeek(ctx context.Context, req *GetListByWeekRpcRequest) (*GetListByWeekRpcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListByWeek not implemented")
}
func (*UnimplementedCalendarServer) GetListByMonth(ctx context.Context, req *GetListByMonthRpcRequest) (*GetListByMonthRpcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListByMonth not implemented")
}

func RegisterCalendarServer(s *grpc.Server, srv CalendarServer) {
	s.RegisterService(&_Calendar_serviceDesc, srv)
}

func _Calendar_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).Create(ctx, req.(*CreateRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).Update(ctx, req.(*UpdateRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).Delete(ctx, req.(*DeleteRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_GetListByDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListByDateRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).GetListByDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/GetListByDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).GetListByDate(ctx, req.(*GetListByDateRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_GetListByWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListByWeekRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).GetListByWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/GetListByWeek",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).GetListByWeek(ctx, req.(*GetListByWeekRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_GetListByMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListByMonthRpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).GetListByMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/GetListByMonth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).GetListByMonth(ctx, req.(*GetListByMonthRpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calendar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Calendar",
	HandlerType: (*CalendarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Calendar_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Calendar_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Calendar_Delete_Handler,
		},
		{
			MethodName: "GetListByDate",
			Handler:    _Calendar_GetListByDate_Handler,
		},
		{
			MethodName: "GetListByWeek",
			Handler:    _Calendar_GetListByWeek_Handler,
		},
		{
			MethodName: "GetListByMonth",
			Handler:    _Calendar_GetListByMonth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calendar.proto",
}
